name: PlatformIO CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Retrieve pip from cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Retrieve PlatformIO from cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.platformio
            .pio/build
            .pio/libdeps
            !.pio/build/**/src
            !.pio/**/firmware.elf
          key: ${{ runner.os }}-${{ hashFiles('platformio.ini', '.github/workflow/**') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Extract build version
        id: get_version
        uses: battila7/get-version-action@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Run PlatformIO
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
        run: pio run
